---
- job:
    name: rpmreq-base
    parent: tox
    abstract: true
    nodeset:
      nodes:
        - name: test-node
          label: f27-oci

- job:
    name: rpmreq-unit
    parent: rpmreq-base
    description: rpmreq unit tests
    vars:
      tox_envlist: unit

- job:
    name: rpmreq-codestyle
    parent: rpmreq-base
    description: rpmreq code style checks
    vars:
      tox_envlist: codestyle

- project:
    check:
      jobs:
        - rpmreq-unit
        - rpmreq-codestyle
    gate:
      jobs:
        - rpmreq-unit
        - rpmreq-codestyle
    release:
      jobs:
        - upload-pypi
